### ISSUE TITLE
Add Espresso Testing

### ISSUE THREAD

**Issue by alistairholmes** [alistairholmes/devjournal#4]
Create an Espresso Test that will add a new note to the database and then be displayed on the JournalActivity.

References:
-https://classroom.udacity.com/courses/ud855/lessons/f0084cc7-2cbc-4b8e-8644-375e8c927167/concepts/19278172-7e08-4c3e-9e96-f89331635208
-https://developer.android.com/training/testing/espresso/setup

Please follow Contribution guidelines in README.md

**Comment by shouxian92** [comment]
Hi i'd like to pick this up if no one is currently working on it 😄

**Comment by megandsouza03** [comment]
Hey 
Do you need to add any other expresso Tests?

**Comment by alistairholmes** [comment]
Hi @megandsouza03 thanks for showing an interest. Thinking of adding new issue that will create an about page, so we would probably need some testing for that too. Would be interested in something like that?

**Comment by alistairholmes** [comment]
If @shouxian92 doesn't manage then you can take over ;)

**Comment by megandsouza03** [comment]
@alistairholmes great I'll be interested in adding tests. Let me know, happy to help 👍
